name: 'Track Deployment'
description: 'Track your deployment to Pre-Production and Production with this GitHub Action'
branding:
  icon: 'activity'
  color: 'white'
inputs:
  vendor-api-key:
    description: >-
      Deployment vendor API Key
    required: true
  deployment-sha:
    description: >-
      The git sha of the deployment to track
    required: true
  repository-url:
    description: >-
      The URL of the repository being tracked
    required: true
  environment: 
    description: >-
      The environment being deployed to
    required: true
    options: 
        - pre
        - prod
runs:
  using: "composite"
  steps:
    - run: |
        Install-Module -Name AWS.Tools.Installer -Force 
        Install-AWSToolsModule AWS.Tools.CloudWatchLogs -Force
      shell: pwsh
    - run: ${{ github.action_path }}/logDeployment.ps1 -sha ${{ inputs.deployment-sha }} -repoUrl ${{ inputs.repository-url }} -env ${{ inputs.environment }} -vendorKey ${{ inputs.vendor-api-key }}
      shell: pwsh
